micronaut:
  application:
    name: veiculoService
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      show_sql: true
      format_sql: true
netty:
  default:
    allocator:
      max-order: 3
kafka:
  booststrap:
    servers: localhost:9092
consul:
  client:
    registration:
      enable: true
    defaltZone: "localhost:8500"
